/**
 * The shape of an event as it travels through SQS, and the predicates both
 * ends of the pipe need to agree on.
 *
 * Splitting this out keeps "what a valid message looks like" in one place: a
 * producer that emits a field the worker does not expect is the kind of bug
 * that only shows up when a message lands in the dead-letter queue.
 */

/** An event as it is enqueued by the producer. */
export interface EventMessage {
  /** Unique id, generated by the producer. Also the idempotency key. */
  readonly eventId: string;
  readonly type: string;
  readonly payload: Record<string, unknown>;
  /** ISO 8601, when the producer accepted the event. */
  readonly receivedAt: string;
}

/** An event record as stored by the worker. */
export interface EventRecord extends EventMessage {
  readonly pk: string;
  readonly sk: string;
  readonly gsi1pk: string;
  readonly gsi1sk: string;
  /** ISO 8601, when the worker finished processing it. */
  readonly processedAt: string;
  /** Unix epoch seconds. DynamoDB TTL deletes the item after this. */
  readonly expiresAt: number;
}

const SECONDS_PER_DAY = 86_400;

/** Unix epoch seconds at which an event received now should expire. */
export function expirationEpoch(ttlDays: number, now: Date = new Date()): number {
  return Math.floor(now.getTime() / 1000) + ttlDays * SECONDS_PER_DAY;
}

/**
 * Parses and checks a message pulled from the queue.
 *
 * Throws rather than returning a result: every failure here means the message
 * is not one this worker can ever process, and the caller's job is to report
 * the message id for retry and eventual dead-lettering.
 */
export function parseEventMessage(body: string): EventMessage {
  const parsed: unknown = JSON.parse(body);

  if (typeof parsed !== 'object' || parsed === null) {
    throw new Error('Message body is not an object');
  }

  const { eventId, type, payload, receivedAt } = parsed as Partial<EventMessage>;

  if (typeof eventId !== 'string' || eventId.length === 0) {
    throw new Error('Message has no eventId');
  }

  if (typeof type !== 'string' || type.length === 0) {
    throw new Error('Message has no type');
  }

  if (typeof receivedAt !== 'string' || Number.isNaN(Date.parse(receivedAt))) {
    throw new Error('Message has no valid receivedAt');
  }

  const resolvedPayload = payload === undefined || payload === null ? {} : payload;

  return { eventId, type, payload: resolvedPayload, receivedAt };
}
